import {createContext} from "react";
import { ConstantBuilder, ThemeConstantProvider, ThemeConstants } from "./types";
import { Theme } from "./Theme";

const _sr = 0.5;

export const defaultDarkThemeConstantsBuilder = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.bkgShade0, '#000000')
    .set(Theme.Colors.bkgShade1, '#111113')
    .set(Theme.Colors.bkgShade2, '#0C1C1E')
    .set(Theme.Colors.bkgShade3, '#39393E')
    .set(Theme.Colors.bkgShade4, '#48484A')
    .set(Theme.Colors.textColor, '#FFFFFF')
    .set(Theme.Colors.highlight, '#FF3B2F')
    .set(Theme.Colors.splash, '#000000')
    .set(Theme.Button.btnPrimary, '#EEEEEE')
    .set(Theme.Button.inverseBtnPrimary, '#888888')
    .set(Theme.Button.btnHighlight, '#FF3B2F')
    .set(Theme.Button.btnPrimaryTextColor, '$Color.bkgShade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#EEEEEE')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 40 * _sr)
    .set(Theme.Button.btnPadding, 55 * _sr)
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Text.textColor, '$Color.textColor')
    .set(Theme.Text.inversTextColor, '#FF3B2F')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#35708F')
    .set(Theme.Text.infoColor, '#EEEEEE')
    .set(Theme.Text.disabledColor, '#818186')
    .set(Theme.Text.h1Size, 55 * _sr)
    .set(Theme.Text.h2Size, 45 * _sr)
    .set(Theme.Text.h3Size, 35 * _sr)
    .set(Theme.Text.h4Size, 30 * _sr)
    .set(Theme.Text.pSize, 40 * _sr)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '$Color.highlight')
    .set(Theme.Page.titleColor, '#000000')
    .set(Theme.Page.titleSize, '$Text.h1Size')
    .set(Theme.Page.titleIconColor, '$Color.textColor')
    .set(Theme.Chart.redGradiantStart, '#000000')
    .set(Theme.Chart.redGradiantEnd, '#99221A')
    .set(Theme.Chart.greenGradiantStart, '#000000')
    .set(Theme.Chart.greenGradiantEnd, '#129996')
    .set(Theme.Input.inputBackground, '#1C1C1E')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50 * _sr)
    .set(Theme.Input.inputLabelSize, 35 * _sr)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45 * _sr)
    .set(Theme.Input.inputLargeLabelColor, "$Color.textColor")
    .set(Theme.List.listItemPaddingTop, 30 * _sr)
    .set(Theme.List.listItemPaddingButtom, 30 * _sr)
    .set(Theme.List.listItemBorderColor, '#D1D1D6')
    .set(Theme.Icon.iconColor, '$Color.bkgShade4')
    .set(Theme.Icon.backgroundColor, '#1C1C1E')
    .set(Theme.Switch.thumbColor, '#D1D1D6')
    .set(Theme.Switch.backgroundColorFalse, '#111113')
    .set(Theme.Switch.backgroundColorTrue, '#1C1C1E')
    .set(Theme.Pin.keyboardBackground, '#1C1C1E')
    .set(Theme.Pin.keyboardTextColor, '#FFFFFF')
    .set(Theme.Pin.bubbleActive, '#FFFFFF')
    .set(Theme.Pin.bubbleInActive, '#1C1C1E')
    .set(Theme.Icon.iconBorderRadius, 5 * _sr)
    .set(Theme.Coin.iconBackground, '$Color.bkgShade2');

export const defaultGreenThemeConstantsBuilder = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.bkgShade0, '#FFFFFF')
    .set(Theme.Colors.bkgShade1, '#f2f2f2')
    .set(Theme.Colors.bkgShade2, '#e3e3e3')
    .set(Theme.Colors.bkgShade3, '#c3c3c3')
    .set(Theme.Colors.bkgShade4, '#474646')
    .set(Theme.List.listItemBorderColor, '#D1D1D6')
    .set(Theme.Switch.thumbColor, '#f2f2f2')
    .set(Theme.Switch.backgroundColorFalse, '#FAFAFA')
    .set(Theme.Switch.backgroundColorTrue, '#26C97A')
    .set(Theme.Colors.textColor, '#111113')
    .set(Theme.Colors.highlight, '#DD1155')
    .set(Theme.Colors.splash, '#26c97a')
    .set(Theme.Button.btnPrimary, '#26C97A')
    .set(Theme.Button.inverseBtnPrimary, '#FAFAFA')
    .set(Theme.Button.btnHighlight, '#DD1155')
    .set(Theme.Button.btnPrimaryTextColor, '$Color.bkgShade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#AAAAAA')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 40 * _sr)
    .set(Theme.Button.btnPadding, 55 * _sr)
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Text.textColor, '$Color.textColor')
    .set(Theme.Text.inversTextColor, '#212121')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#26C97A')
    .set(Theme.Text.infoColor, '#212121')
    .set(Theme.Text.disabledColor, '#818186')
    .set(Theme.Text.h1Size, 55 * _sr)
    .set(Theme.Text.h2Size, 45 * _sr)
    .set(Theme.Text.h3Size, 35 * _sr)
    .set(Theme.Text.h4Size, 30 * _sr)
    .set(Theme.Text.pSize, 40 * _sr)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '#FF3B2F')
    .set(Theme.Page.titleColor, '#26C97A')
    .set(Theme.Page.titleSize, '$Text.h1Size')
    .set(Theme.Page.titleIconColor, '$Color.textColor')
    .set(Theme.Chart.redGradiantStart, '#000000')
    .set(Theme.Chart.redGradiantEnd, '#FAFAFA')
    .set(Theme.Chart.greenGradiantStart, '#000000')
    .set(Theme.Chart.greenGradiantEnd, '#FF392C')
    .set(Theme.Input.inputBackground, '#26C97A')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50 * _sr)
    .set(Theme.Input.inputLabelSize, 35 * _sr)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45 * _sr)
    .set(Theme.Input.inputLargeLabelColor, "$Color.textColor")
    .set(Theme.List.listItemPaddingTop, 30 * _sr)
    .set(Theme.List.listItemPaddingButtom, 30 * _sr)
    .set(Theme.Icon.iconColor, '$Button.btnPrimary')
    .set(Theme.Icon.backgroundColor, '#212121')
    .set(Theme.Pin.keyboardBackground, '#111113')
    .set(Theme.Pin.keyboardTextColor, '#FAFAFA')
    .set(Theme.Pin.bubbleActive, '#FFFFFF')
    .set(Theme.Pin.bubbleInActive, '#26C97A')
    .set(Theme.Icon.iconBorderRadius, 5 * _sr)
    .set(Theme.Coin.iconBackground, '$Color.bkgShade3');

export const WebdefaultDarkThemeConstantsBuilder = (theme:any) => {
    return ConstantBuilder.builder<string|number, ThemeConstants>()
    .set('bkgShade0', theme.palette.white)
    .set('bkgShade2', '#0C1C1E')
    .set('bkgShade5', '#FFFFFF')
    .set(Theme.Logo.logo, theme.palette.logoUrl )
    .set(Theme.Colors.themeNavBkg, theme.palette.themeNavLight)
    .set('headerTextColor', 'orange')
    .set(Theme.Colors.headerTextColor, 'orange')
    .set(Theme.Colors.textColor, '#111113')
    .set(Theme.Colors.highlight, '#DD1155')
}

export const WebdefaultLightThemeConstantsBuilder = (theme:any) => {
    return ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.headerTextColor, 'orange')
    .set(Theme.Logo.logo, theme.palette.logoUrl )
    .set(Theme.Colors.themeNavBkg, theme.palette.themeNavLight)
    .set(Theme.Colors.textColor, '#111113')
    .set(Theme.Colors.highlight, '#DD1155')
}

export const defaultFerrumThemeConstantsBuilder = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.bkgShade0, '#FFFFFF')
    .set(Theme.Colors.bkgShade1, '#f2f2f2')
    .set(Theme.Colors.bkgShade2, '#e3e3e3')
    .set(Theme.Colors.bkgShade3, '#c3c3c3')
    .set(Theme.Colors.bkgShade4, '#474646')
    .set(Theme.List.listItemBorderColor, '#D1D1D6')
    .set(Theme.Switch.thumbColor, '#f2f2f2')
    .set(Theme.Switch.backgroundColorFalse, '#FAFAFA')
    .set(Theme.Switch.backgroundColorTrue, '#26C97A')
    .set(Theme.Colors.textColor, '#111113')
    .set(Theme.Colors.highlight, '#DD1155')
    .set(Theme.Colors.splash, '#26c97a')
    .set(Theme.Button.btnPrimary, '#26C97A')
    .set(Theme.Button.inverseBtnPrimary, '#FAFAFA')
    .set(Theme.Button.btnHighlight, '#DD1155')
    .set(Theme.Button.btnPrimaryTextColor, '$Color.bkgShade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#AAAAAA')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 40 * _sr)
    .set(Theme.Button.btnPadding, 55 * _sr)
    .set(Theme.Text.textColor, '$Color.textColor')
    .set(Theme.Text.inversTextColor, '#212121')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#26C97A')
    .set(Theme.Text.infoColor, '#212121')
    .set(Theme.Text.disabledColor, '#818186')
    .set(Theme.Text.h3Size, 35 * _sr)
    .set(Theme.Text.h4Size, 30 * _sr)
    .set(Theme.Text.pSize, 40 * _sr)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '#FF3B2F')
    .set(Theme.Page.titleColor, '#26C97A')
    .set(Theme.Page.titleSize, '$Text.h1Size')
    .set(Theme.Page.titleIconColor, '$Color.textColor')
    .set(Theme.Chart.redGradiantStart, '#D33127')
    .set(Theme.Chart.redGradiantEnd, '#FAFAFA')
    .set(Theme.Chart.greenGradiantStart, '#258B66')
    .set(Theme.Chart.greenGradiantEnd, '#26C97A')
    .set(Theme.Input.inputBackground, '#26C97A')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50 * _sr)
    .set(Theme.Input.inputLabelSize, 35 * _sr)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45 * _sr)
    .set(Theme.Input.inputLargeLabelColor, "$Color.textColor")
    .set(Theme.List.listItemPaddingTop, 30 * _sr)
    .set(Theme.List.listItemPaddingButtom, 30 * _sr)
    .set(Theme.Icon.iconColor, '$Button.btnPrimary')
    .set(Theme.Icon.backgroundColor, '#212121')
    .set(Theme.Pin.keyboardBackground, '#111113')
    .set(Theme.Pin.keyboardTextColor, '#FAFAFA')
    .set(Theme.Pin.bubbleActive, '#FFFFFF')
    .set(Theme.Pin.bubbleInActive, '#26C97A')
    .set(Theme.Icon.iconBorderRadius, 5 * _sr)
    .set(Theme.Coin.iconBackground, '$Color.bkgShade3')
    // Start
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Colors.dark, '#26272B')
    .set(Theme.Colors.darkLight, '#31353C')
    .set(Theme.Colors.greyDark, '#898B8F')
    .set(Theme.Colors.greyMedium, '#B5B6B8')
    .set(Theme.Colors.greyLight, '#C5C5C7')
    .set(Theme.Colors.gold, '#C9A566')
    .set(Theme.Colors.green, '#00B929')
    .set(Theme.Colors.red, '#D33127')
    .set(Theme.Colors.off, '#F3F3F3')
    .set(Theme.Colors.white, '#FFFFFF')
    .set(Theme.Text.h1Size, 24)
    .set(Theme.Text.h2Size, 16)
    .set(Theme.Text.labelSize, 14)
    .set(Theme.Text.smallLabel, 12)
    .set(Theme.Text.tinyLabel, 10)

export const ThemeContext = createContext<ThemeConstantProvider>(
    new ThemeConstantProvider('ferrum', defaultFerrumThemeConstantsBuilder.build()));
