import {createContext} from "react";
import { ConstantBuilder, ThemeConstantProvider, ThemeConstants } from "./types";
import { Theme } from "./Theme";

export const defaultDarkThemeConstants = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50)
    .set(Theme.Spaces.screenMarginVertical, 30)
    .set(Theme.Spaces.gap, 60)
    .set(Theme.Spaces.line, 30)
    .set(Theme.Colors.bkgShade0, '#000000')
    .set(Theme.Colors.bkgShade1, '#111113')
    .set(Theme.Colors.bkgShade2, '#1C1C1E')
    .set(Theme.Colors.bkgShade3, '#48484A')
    .set(Theme.Colors.bkgShade4, '#8E8E93')
    .set(Theme.Colors.bkgShade5, '#EEEEEE')
    .set(Theme.Colors.bkgShade6, '#EEEEEE')
    .set(Theme.Colors.bkgShade7, '#EEEEEE')
    .set(Theme.Colors.bkgShade8, '#FFFFFF')
    .set(Theme.Colors.textColor, '#FFFFFF')
    .set(Theme.Colors.highlight, '#FF3B2F')
    .set(Theme.Button.btnPrimary, '#EEEEEE')
    .set(Theme.Button.inverseBtnPrimary, '#000000')
    .set(Theme.Button.btnHighlight, '#FF3B2F')
    .set(Theme.Button.btnPrimaryTextColor, '$Colors.btnSade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#FFFFFF')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 10)
    .set(Theme.Button.btnPadding, 55)
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Text.textColor, '$Colors.textColor')
    .set(Theme.Text.inversTextColor, '$Colors.bkgShade0')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#D1D1D6')
    .set(Theme.Text.infoColor, '#EDEDED')
    .set(Theme.Text.h1Size, 55)
    .set(Theme.Text.h2Size, 45)
    .set(Theme.Text.h3Size, 35)
    .set(Theme.Text.h4Size, 30)
    .set(Theme.Text.pSize, 40)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '$Colors.highlight')
    .set(Theme.Page.titleColor, '$Colors.textColor')
    .set(Theme.Page.titleSize, '$Colors.h1Size')
    .set(Theme.Page.titleIconColor, '$Colors.titleIconColor')
    .set(Theme.Chart.redGradiantStart, '#000000')
    .set(Theme.Chart.redGradiantEnd, '#FF392C')
    .set(Theme.Input.inputBackground, '#1C1C1E')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50)
    .set(Theme.Input.inputLabelSize, 35)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45)
    .set(Theme.Input.inputLargeLabelColor, "$Colors.textColor")
    .set(Theme.List.listItemPaddingTop, 30)
    .set(Theme.List.listItemPaddingButtom, 30)
    .set(Theme.Icon.iconColor, '$Colors.bkgShade2')
    .set(Theme.Icon.backgroundColor, '$Colors.backgroundColor')
    .set(Theme.Icon.iconBorderRadius, '$Colors.iconBorderRadius')
    .build();

export const ThemeContext = createContext<ThemeConstantProvider>(
    new ThemeConstantProvider('unifyre', defaultDarkThemeConstants));

