import {createContext} from "react";
import { ConstantBuilder, ThemeConstantProvider, ThemeConstants } from "./types";
import { Theme } from "./Theme";

const _sr = 0.5;

export const defaultDarkThemeConstantsBuilder = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.bkgShade0, '#000000')
    .set(Theme.Colors.bkgShade1, '#111113')
    .set(Theme.Colors.bkgShade2, '#1C1C1E')
    .set(Theme.Colors.bkgShade3, '#48484A')
    .set(Theme.Colors.bkgShade4, '#FF3B2F')
    .set(Theme.Colors.bkgShade5, '#EEEEEE')
    .set(Theme.Colors.bkgShade6, '#09090A')
    .set(Theme.Colors.bkgShade7, '#1C1C1E')
    .set(Theme.Colors.bkgShade8, '#FFFFFF')
    .set(Theme.Colors.textColor, '#FFFFFF')
    .set(Theme.Colors.highlight, '#FF3B2F')
    .set(Theme.Button.btnPrimary, '#EEEEEE')
    .set(Theme.Button.inverseBtnPrimary, '#000000')
    .set(Theme.Button.btnHighlight, '#FF3B2F')
    .set(Theme.Button.btnPrimaryTextColor, '$Color.bkgShade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#FFFFFF')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 10 * _sr)
    .set(Theme.Button.btnPadding, 55 * _sr)
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Text.textColor, '$Color.textColor')
    .set(Theme.Text.inversTextColor, '#FF3B2F')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#D1D1D6')
    .set(Theme.Text.infoColor, '#000000')
    .set(Theme.Text.h1Size, 55 * _sr)
    .set(Theme.Text.h2Size, 45 * _sr)
    .set(Theme.Text.h3Size, 35 * _sr)
    .set(Theme.Text.h4Size, 30 * _sr)
    .set(Theme.Text.pSize, 40 * _sr)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '$Color.highlight')
    .set(Theme.Page.titleColor, '#000000')
    .set(Theme.Page.titleSize, '$Text.h1Size')
    .set(Theme.Page.titleIconColor, '$Color.textColor')
    .set(Theme.Chart.redGradiantStart, '#000000')
    .set(Theme.Chart.redGradiantEnd, '#FF392C')
    .set(Theme.Input.inputBackground, '#1C1C1E')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50 * _sr)
    .set(Theme.Input.inputLabelSize, 35 * _sr)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45 * _sr)
    .set(Theme.Input.inputLargeLabelColor, "$Color.textColor")
    .set(Theme.List.listItemPaddingTop, 30 * _sr)
    .set(Theme.List.listItemPaddingButtom, 30 * _sr)
    .set(Theme.List.listItemBorderColor, '#D1D1D6')
    .set(Theme.Icon.iconColor, '$Color.bkgShade2')
    .set(Theme.Icon.backgroundColor, '#1C1C1E')
    .set(Theme.Switch.thumbColor, '#D1D1D6')
    .set(Theme.Switch.backgroundColorFalse, '#111113')
    .set(Theme.Switch.backgroundColorTrue, '#1C1C1E')
    .set(Theme.Pin.keyboardBackground, '#1C1C1E')
    .set(Theme.Pin.keyboardTextColor, '#FFFFFF')
    .set(Theme.Pin.bubbleActive, '#FFFFFF')
    .set(Theme.Pin.bubbleInActive, '#1C1C1E')
    .set(Theme.Icon.iconBorderRadius, 5 * _sr)
    .set(Theme.Coin.iconBackground, '$Color.bkgShade3');

export const defaultGreenThemeConstantsBuilder = ConstantBuilder.builder<string|number, ThemeConstants>()
    .set(Theme.Spaces.screenMarginHorizontal, 50 * _sr)
    .set(Theme.Spaces.screenMarginVertical, 30 * _sr)
    .set(Theme.Spaces.gap, 60 * _sr)
    .set(Theme.Spaces.line, 30 * _sr)
    .set(Theme.Colors.bkgShade0, '#FFFFFF')
    .set(Theme.Colors.bkgShade1, '#f2f2f2')
    .set(Theme.List.listItemBorderColor, '#D1D1D6')
    .set(Theme.Switch.thumbColor, '#f2f2f2')
    .set(Theme.Switch.backgroundColorFalse, '#FAFAFA')
    .set(Theme.Switch.backgroundColorTrue, '#26C97A')
    .set(Theme.Colors.bkgShade2, '#1C1C1E')
    .set(Theme.Colors.bkgShade3, '#FFFFFF')
    .set(Theme.Colors.bkgShade4, '#FFFFFF')
    .set(Theme.Colors.bkgShade5, '#EEEEEE')
    .set(Theme.Colors.bkgShade6, '#FAFAFA')
    .set(Theme.Colors.bkgShade7, '#212121')
    .set(Theme.Colors.bkgShade8, '#FFFFFF')
    .set(Theme.Colors.textColor, '#111113')
    .set(Theme.Colors.highlight, '#26C97A')
    .set(Theme.Button.btnPrimary, '#26C97A')
    .set(Theme.Button.inverseBtnPrimary, '#FAFAFA')
    .set(Theme.Button.btnHighlight, '#26C97A')
    .set(Theme.Button.btnPrimaryTextColor, '$Color.bkgShade1')
    .set(Theme.Button.inverseBtnPrimaryTextColor, '#AAAAAA')
    .set(Theme.Button.btnHighlightTextColor, '#FFFFFF')
    .set(Theme.Button.btnBorderRadius, 10 * _sr)
    .set(Theme.Button.btnPadding, 55 * _sr)
    .set(Theme.Font.main, 'SF Pro Text')
    .set(Theme.Text.textColor, '$Color.textColor')
    .set(Theme.Text.inversTextColor, '#212121')
    .set(Theme.Text.subTextColor, '#D1D1D6')
    .set(Theme.Text.linkColor, '#D1D1D6')
    .set(Theme.Text.infoColor, '#212121')
    .set(Theme.Text.h1Size, 55 * _sr)
    .set(Theme.Text.h2Size, 45 * _sr)
    .set(Theme.Text.h3Size, 35 * _sr)
    .set(Theme.Text.h4Size, 30 * _sr)
    .set(Theme.Text.pSize, 40 * _sr)
    .set(Theme.Text.numberUpColor, '#00FF40')
    .set(Theme.Text.numberDownColor, '#FF3B2F')
    .set(Theme.Page.titleColor, '#26C97A')
    .set(Theme.Page.titleSize, '$Text.h1Size')
    .set(Theme.Page.titleIconColor, '$Color.textColor')
    .set(Theme.Chart.redGradiantStart, '#000000')
    .set(Theme.Chart.redGradiantEnd, '#FAFAFA')
    .set(Theme.Input.inputBackground, '#26C97A')
    .set(Theme.Input.inputTextColor, '#FFFFFF')
    .set(Theme.Input.inputTextSize, 50 * _sr)
    .set(Theme.Input.inputLabelSize, 35 * _sr)
    .set(Theme.Input.inputLabelColor, '#D1D1D6')
    .set(Theme.Input.inputLargeLabelSize, 45 * _sr)
    .set(Theme.Input.inputLargeLabelColor, "$Color.textColor")
    .set(Theme.List.listItemPaddingTop, 30 * _sr)
    .set(Theme.List.listItemPaddingButtom, 30 * _sr)
    .set(Theme.Icon.iconColor, '$Color.bkgShade2')
    .set(Theme.Icon.backgroundColor, '#212121')
    .set(Theme.Pin.keyboardBackground, '#111113')
    .set(Theme.Pin.keyboardTextColor, '#FAFAFA')
    .set(Theme.Pin.bubbleActive, '#FFFFFF')
    .set(Theme.Pin.bubbleInActive, '#26C97A')
    .set(Theme.Icon.iconBorderRadius, 5 * _sr)
    .set(Theme.Coin.iconBackground, '$Color.textColor');

export const ThemeContext = createContext<ThemeConstantProvider>(
    new ThemeConstantProvider('unifyre', defaultGreenThemeConstantsBuilder.build()));
